import { defineConfig } from 'oxlint'

export default defineConfig({
  ignorePatterns: [
    '**/.agent/**',
    '**/.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    'scripts/oxlint/anti-slop/**',
    '**/node_modules/**',
    '**/.next/**',
    '**/dist/**',
    '**/.turbo/**',
    '**/.generated/**',
    '**/coverage/**',
    '**/docs/**',
    '**/scripts/**',
    'scripts/**',
    '**/*.config.*',
    '**/*.d.ts',
    '**/*.test.*',
    '**/*.spec.*',
    '**/*.stories.*',
    '**/.storybook/**',
    '**/e2e/**',
    '**/tests/**',
  ],
  jsPlugins: ['./scripts/oxlint/anti-slop/index.ts'],
  rules: {
    'eslint/no-console': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },
})
